"""sync_sa_models

Revision ID: 53b0f6708a81
Revises: 76b268b78a8b
Create Date: 2026-05-19 10:09:44.165390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b0f6708a81'
down_revision: Union[str, None] = '76b268b78a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('code', sa.String(), nullable=True))
    op.create_index(op.f('ix_disciplines_code'), 'disciplines', ['code'], unique=True)
    op.add_column('reference_graphs', sa.Column('graph_data', sa.JSON(), nullable=True))
    op.add_column('reference_graphs', sa.Column('discipline_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_reference_graphs_discipline_id_disciplines',
        'reference_graphs',
        'disciplines',
        ['discipline_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.add_column('student_attempts', sa.Column('reference_graph_id', sa.Integer(), nullable=True))
    op.add_column('student_attempts', sa.Column('submitted_graph', sa.JSON(), nullable=True))
    op.add_column('student_attempts', sa.Column('metrics', sa.JSON(), nullable=True))
    op.add_column('student_attempts', sa.Column('algorithm_version', sa.String(), nullable=True))
    op.add_column('student_attempts', sa.Column('reference_content_hash', sa.String(), nullable=True))
    op.add_column('student_attempts', sa.Column('embedding_model_version', sa.String(), nullable=True))
    op.add_column('student_attempts', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS uq_student_attempt_idempotency_key
        ON student_attempts (student_id, idempotency_key)
        WHERE idempotency_key IS NOT NULL
        """
    )
    op.alter_column('student_attempts', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('student_attempts', 'student_graph',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_foreign_key(
        'fk_student_attempts_reference_graph_id_reference_graphs',
        'student_attempts',
        'reference_graphs',
        ['reference_graph_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS uq_student_attempt_idempotency_key")
    op.drop_constraint(
        'fk_student_attempts_reference_graph_id_reference_graphs',
        'student_attempts',
        type_='foreignkey',
    )
    op.alter_column('student_attempts', 'student_graph',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('student_attempts', 'assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('student_attempts', 'idempotency_key')
    op.drop_column('student_attempts', 'embedding_model_version')
    op.drop_column('student_attempts', 'reference_content_hash')
    op.drop_column('student_attempts', 'algorithm_version')
    op.drop_column('student_attempts', 'metrics')
    op.drop_column('student_attempts', 'submitted_graph')
    op.drop_column('student_attempts', 'reference_graph_id')
    op.drop_constraint(
        'fk_reference_graphs_discipline_id_disciplines',
        'reference_graphs',
        type_='foreignkey',
    )
    op.drop_column('reference_graphs', 'discipline_id')
    op.drop_column('reference_graphs', 'graph_data')
    op.drop_index(op.f('ix_disciplines_code'), table_name='disciplines')
    op.drop_column('disciplines', 'code')
    # ### end Alembic commands ###
